---
about:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Early life

Sarah M. Coleman, an Austin, Texas, native, graduated from L.C. Anderson High School, also recieving a [International Baccalaureate](https://ibo.org/programmes/diploma-programme/) (IB) Diploma. The L.C. Anderson science faculty awarded her with the Bob Furtado scholarship, given to the student most passionate about science in every graduating class. Sarah was also a high school athlete, and rowed on the varsity team at [Texas Rowing Center](https://www.texasrowingcenter.com/). In 2014, she was recognized nationally as a recipient of the [2014-2015 US Rowing Scholastic Honor Roll](https://justicerowing.org/wp-content/uploads/2014/11/Press-Releases-USRowing-Announces-2014-15-Scholastic-Honor-Roll.pdf). Her proudest rowing career achievement was stroking a double at the Head of the Charles Regatta in 2014.

### Undergraduate work

Sarah started in MIT in Fall 2015. There, she performed undergradaute research with [Dr. Gregory Stephanopoulos](https://stephanopouloslab.mit.edu/) (retired) for two years and [Dr. Michael Strano](https://srg.mit.edu/) for one year. With Dr. Stephanopolous, she developed anaerobic assays to evaluate enzymes involved in carbon dioxide assimilation. With Dr. Strano, she helped improve the emission properties of nanoparticles embedded in a living plant. Her research with Dr. Strano assisted in an [art exhibit at the Cooper Hewitt, Smithsonian Design Museum](https://news.mit.edu/2019/ambient-plant-illumination-could-light-way-greener-buildings-0510) in Summer 2019. Sarah graduated with a S.B. in Chemical-Biological Engineering in Spring 2019.

While at MIT, Sarah spent her summers interning in pharmaceutical process development for vaccine production at [Takeda Pharmaceuticals](https://www.takeda.com/science/areas-of-focus/vaccines/) and cancer therapeutics at [Bristol-Myers Squibb](https://www.bms.com/). Sarah also worked as a math tutor for a local nonprofit, [Girls' Angle](https://www.girlsangle.org/). Sarah was also a student leader; at MIT, she served as the President of the [MIT AIChE Chapter](https://aiche.scripts.mit.edu/) and the Program Administrator of the Chemical Engineering Freshman Pre-Orientation Program (FPOP). She was also a first and second year-leader in [MIT's Gordon Engineering Leadership Program](https://gelp.mit.edu/).

### Graduate work

In Fall 2019, Sarah M. Coleman began her doctoral research with [Dr. Hal S. Alper](https://utw10252.utweb.utexas.edu/) in the Department of Chemical Engineering at The University of Texas at Austin. Sarah defended her PhD in Summer 2024, with a dissertation entitled "A Yeast Grease Feast: Expanding waste valorization by *Yarrowia* clade yeasts to nontraditional and hydrophobic substrates". Her graduate work focused on the evolution and engineering of *Yarrowia* clade yeasts to metabolize waste and produce industrially relevant chemicals. She was a productive graduate student, with [five publications at the first- or co-first authorship level]{.underline} and 11 authorships in total resulting from her PhD (see Publications).

Sarah's early graduate work was supported financially by the prestigious Provost's Excellence Fellowship and Thrust Fellowship. In Spring 2021, Sarah was awarded the [NSF GRFP](https://www.nsfgrfp.org/) as a second-year graduate student. In 2022, Sarah was awarded the [Green Fund Grant](https://sustainability.utexas.edu/green-fund/funded-projects) from The University of Texas at Austin Department of Sustainability to support her doctoral research into waste cooking oil valorization.

On top of all her late nights and weekends in lab, Sarah took additional graduate courses in advanced statistics, bioinformatics, and machine learning. This allowed her to receive a M.S. in Statistics in Spring 2024. To the best of her knowledge, Sarah is the only student in her doctoral program who graduated in five years with an M.S. in a different discipline. Sarah brought her computational experience back to her PhD group, where she became the TACC (Texas Advanced Computing Center) project lead and hosted trainings to familiarize the rest of her group with these techniques. Although she now considers herself more proficient in languages such as R and Python, Sarah will never forget her first programming language, MATLAB. In fact, Sarah served as the [MATLAB and Simulink Student Ambassador](https://www.mathworks.com/academia/students/student-ambassadors.html) for the University of Texas at Austin from 2020 to 2021.

Sarah also continued her student leadership throughout her PhD. At UT Austin, she served as the President (previously serving as Outreach Coordinator and Enrichment Chair) of the Chemical Engineering [Graduate Leadership Council (ChE GLC)](https://utexas.campuslabs.com/engage/organization/graduatechemicalengineeringleadershipcouncil). She also organized the weekly 1st and 3rd year Graduate Student Seminars from 2021-2022 and served as a graduate recruitment chair for the 2020 season.

### Postdoctoral work

In Fall 2024, Sarah started as a Postdoctoral Research Fellow in Environmental Biostatistics with [Dr. Roger D. Peng](https://rdpeng.org/) in the Department of Statistics and Data Sciences at The University of Texas at Austin. Sarah had enjoyed her statistics classes in graduate school immensely and was excited for the opportunity to conduct academic research in this area full time. With Roger, Sarah is interested in studying what interventions are be the most helpful to reduce the harmfulness of air pollution, and how effective current interventions are.

As an engineer at heart surrounded by career data scientists and statisticians, Sarah began fostering connections and relationships in her new department. In Summer 2025, Sarah (presenting author) [won the Professional division](https://stat.utexas.edu/news/features/sds-postdoctoral-fellows-receive-award-joint-statistical-meetings-jsm-2025) of the JSM Data Science Expo Challenge, along with three other UT Austin postdoctoral fellows.

Sarah was unable to TA in graduate school due to fellowship logistics; however, she had always wanted to experience teaching at the university level. In Spring 2026, Sarah was nominated by her advisor Roger to serve as the Instructor of Record for an upper-level undergraduate course at UT, Elements of Data Science (SDS 322E). In this role she managed the entire course, and also supervised three teaching assistants. Sarah really enjoyed the opportunity to lecture on the skills she learned as a graduate student, and tie them into her real-world wet-lab background.

### Career

After her postdoctoral fellowship, Sarah returned to her original PhD field. Sarah began working with [BioReNuva](https://biorenuva.com/) in Austin, TX as a bioprocess development engineer in Summer 2026. With BioReNuva, Sarah is helping to develop the microbial production of surfactants for a variety of commercial uses.

### Fun facts

- Sarah founded a club at MIT, Fruit Club, with a former roommate. The motto of Fruit Club is "When life gives you lemons, bring them to Fruit Club"!

- [Sarah's Academic Family Tree](https://utw10252.utweb.utexas.edu/Geneaology.html) (based on her PhD advisor lineage) goes back to the 1400s and includes Isaac Newton!

- Sarah loves to garden. Her favorite thing she's ever grown is a [romanesco cauliflower](https://en.wikipedia.org/wiki/Romanesco_broccoli).

- Sarah has a corgi named Chief! He is almost two years old.

- Sarah LOVES fermentation both in and out of the lab, and is an avid kombucha brewer and sourdough baker. She gave a public talk about edible fermentation to [Nerd Nite Austin](https://youtu.be/ZbzBi3qKho0?) in January 2026.
